### ISSUE TITLE
air_update_data_frame() not found

### ISSUE THREAD

**Issue by vjbrady68** [ecohealthalliance/airtabler#12]
I've been using your code from the original bergant/airtabler package pull request, particularly the air_update_data_frame command, for several months now to update data to various AT bases. I created a separate script with your function definitions that I run before all of my codes that touch airtable. It has been a LIFESAVOR! Within the last week or so I've started to run into issues with the air_update_data_frame command. I was getting a 404 error. I did some initial troubleshooting b/c I wanted to rule out some sort of weirdness with my data that could have been causing the issue (different column names/types). 

I realized today that you had created your own fork of the package with those updates from the pull request incorporated. So I deleted the bergant version of the package from my package library and installed yours. I see the air_update_data_frame command in the documentation, but I'm getting a "could not find function air_update_data_frame" error now when using your version of the package. Any thoughts on this or the 404 error?

screenshot of the 404 error traceback https://user-images.githubusercontent.com/14184370/176188382-81a39639-39d1-4495-97dc-ca12d9e5aaed.png

**Comment by collinschwantes** [comment]
Using the following code I was able to successfully update the records in this base. 

```
# test air_update_data_frame

base <- "appXXXXXXXXXXX"
table_name <- "test_air_update_data_frame"

demo_records<- fetch_all(base,table_name)

update_records <- demo_records[c(1,3)]

update_records$Notes <- "Updated Records"

air_update_data_frame(base = base,table_name = table_name,record_ids =update_records$id,records = update_records )
```
Error  404 messages generally indicate that a web resource can't be found. airtabler gives an informative message if the table can't be found, but returns a general 404 error if a record can't be found. 

```
# this gives a general 404 error
air_update_data_frame(base = base,table_name = table_name,record_ids =paste0("rec",1:3),records = update_records )

``` 

Check that your record id's are correct and let me know how it goes.

**Comment by vjbrady68** [comment]
Thank you so much for getting back to me so quickly!! Your example was really helpful, I was using such a mix of old airtabler commands and functionality and I think that was messing things up. My base reference was a list object instead of a string - once I matched your structure of things, it all worked! Also, I specifically used the table id from the API documentation vs. the table name which I had been using previously.
